version: '3.4'

services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  energymarketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

