version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
        - "8081:80"

  energymarketapi:
    image: ${DOCKER_REGISTRY-}energymarketapi
    build:
      context: .
      dockerfile: EnergyMarketApi/Dockerfile

